
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostLoanMobileWebServiceHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostLoanMobileWebServiceHttpGet {


    /**
     * 在线业务平台贷后数据提供
     * 
     * @param identNo
     * @param contractNo
     * @param businessID
     * @return
     *     returns mypackage.ArrayOfLoanOrderInfo
     */
    @WebMethod(operationName = "Excute")
    @WebResult(name = "ArrayOfLoanOrderInfo", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfLoanOrderInfo excute(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "identNo")
        String identNo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "businessID")
        String businessID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contractNo")
        String contractNo);

    /**
     * 判断客户是否首次还款后连续6期正常还款
     * 
     * @param idCardNo
     * @return
     *     returns mypackage.RequestResult
     */
    @WebMethod
    @WebResult(name = "RequestResult", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RequestResult checkNormalRepaymentSixMonth(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "IDCardNo")
        String idCardNo);

    /**
     * 加贷再贷条件判断
     * 
     * @param idNo
     * @return
     *     returns mypackage.RequestResult
     */
    @WebMethod(operationName = "IsOpenLoanAgain")
    @WebResult(name = "RequestResult", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RequestResult isOpenLoanAgain(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "IDNo")
        String idNo);

}
