
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostLoanMobileWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.1.12.52:8090/OBizWebService/GateWay/PostLoanMobileWebService.asmx?wsdl")
public class PostLoanMobileWebService
    extends Service
{

    private final static URL POSTLOANMOBILEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException POSTLOANMOBILEWEBSERVICE_EXCEPTION;
    private final static QName POSTLOANMOBILEWEBSERVICE_QNAME = new QName("http://tempuri.org/", "PostLoanMobileWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.12.52:8090/OBizWebService/GateWay/PostLoanMobileWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTLOANMOBILEWEBSERVICE_WSDL_LOCATION = url;
        POSTLOANMOBILEWEBSERVICE_EXCEPTION = e;
    }

    public PostLoanMobileWebService() {
        super(__getWsdlLocation(), POSTLOANMOBILEWEBSERVICE_QNAME);
    }

    public PostLoanMobileWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTLOANMOBILEWEBSERVICE_QNAME, features);
    }

    public PostLoanMobileWebService(URL wsdlLocation) {
        super(wsdlLocation, POSTLOANMOBILEWEBSERVICE_QNAME);
    }

    public PostLoanMobileWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTLOANMOBILEWEBSERVICE_QNAME, features);
    }

    public PostLoanMobileWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostLoanMobileWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostLoanMobileWebServiceSoap
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceSoap")
    public PostLoanMobileWebServiceSoap getPostLoanMobileWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceSoap"), PostLoanMobileWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostLoanMobileWebServiceSoap
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceSoap")
    public PostLoanMobileWebServiceSoap getPostLoanMobileWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceSoap"), PostLoanMobileWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PostLoanMobileWebServiceSoap
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceSoap12")
    public PostLoanMobileWebServiceSoap getPostLoanMobileWebServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceSoap12"), PostLoanMobileWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostLoanMobileWebServiceSoap
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceSoap12")
    public PostLoanMobileWebServiceSoap getPostLoanMobileWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceSoap12"), PostLoanMobileWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PostLoanMobileWebServiceHttpGet
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceHttpGet")
    public PostLoanMobileWebServiceHttpGet getPostLoanMobileWebServiceHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceHttpGet"), PostLoanMobileWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostLoanMobileWebServiceHttpGet
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceHttpGet")
    public PostLoanMobileWebServiceHttpGet getPostLoanMobileWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceHttpGet"), PostLoanMobileWebServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns PostLoanMobileWebServiceHttpPost
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceHttpPost")
    public PostLoanMobileWebServiceHttpPost getPostLoanMobileWebServiceHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceHttpPost"), PostLoanMobileWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostLoanMobileWebServiceHttpPost
     */
    @WebEndpoint(name = "PostLoanMobileWebServiceHttpPost")
    public PostLoanMobileWebServiceHttpPost getPostLoanMobileWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PostLoanMobileWebServiceHttpPost"), PostLoanMobileWebServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTLOANMOBILEWEBSERVICE_EXCEPTION!= null) {
            throw POSTLOANMOBILEWEBSERVICE_EXCEPTION;
        }
        return POSTLOANMOBILEWEBSERVICE_WSDL_LOCATION;
    }

}
